config:
  credentials: []
  project_repos:
    earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer:
      branch: master
      repo: https://earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-eggplant-ferret.sh
        container: qc.acc_geeky-tangerine-havanese
  QC.Doc:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-corn-liger.sh
        container: qc.doc_snoopy-copper-paradise
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-plum-toad.sh
        container: qc.doc_squirrely-auburn-lemur
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-thistle-peccary.sh
        container: qc.doc_shaggy-plum-toad
  QC.Lic:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cinnabar-harrier.sh
        container: qc.lic_cozy-tomato-koala
  QC.Sec:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-salmon-shrimp.sh
        container: qc.sec_flimsy-black-wasp
  QC.Sty:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-apricot-stingray.sh
        container: qc.sty_wimpy-cream-earwig
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-puce-flamingo.sh
        container: qc.sty_nerdy-teal-crocodile
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-pumpkin-flamingo.sh
        container: qc.sty_chummy-copper-discus
  QC.Ver:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-chartreuse-uguisu.sh
        container: qc.ver_scummy-persimmon-hyrax
timeout: 1800
